### PR TITLE
Unpacker updates

### PR DESCRIPTION
**Pull request by spaulaus**
This merge will allow for the last major phase before we have PAASS v1. This also fixes issues with scope. 

(Got the right two branches this time. )

### CODE REVIEW

**Comment by ksmith0** [comment]
I suggest @cthornsb accepts this merge request as he is most familiar with the commits.

**Comment by ksmith0** [comment]
I may want to try this new scope out to see if the functionality is the same as previously.

**Comment by spaulaus** [comment]
Cory did some tests and everything was clean. I don't know that we have to worry **too** much, this is what the dev branch is for after all.

**Comment by spaulaus** [comment]
@cthornsb Any word on confirming this request?

**Pull request merged**
